# Generated by Django 4.2.20 on 2025-04-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wbs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
